bin2c -o solid_frag.h shader_solid.frag
bin2c -o solid_vert.h shader_solid.vert
bin2c -o solid_color_frag.h shader_solid_color.frag
bin2c -o solid_color_vert.h shader_solid_color.vert
bin2c -o texture_color_rgb_transform_frag.h shader_texture_color_rgb_transform.frag
bin2c -o texture_color_frag.h shader_texture_color.frag
bin2c -o texture_color_vert.h shader_texture_color.vert
bin2c -o texture_color_frag_paint.h shader_texture_color_paint.frag
bin2c -o texture_color_vert_paint.h shader_texture_color_paint.vert
bin2c -o texture_color_fog_frag.h shader_texture_color_fog.frag
bin2c -o texture_color_fog_vert.h shader_texture_color_fog.vert
bin2c -o texture_color_hsv_fog_frag.h shader_texture_color_hsv_fog.frag
bin2c -o texture_color_hsv_fog_vert.h shader_texture_color_hsv_fog.vert
bin2c -o texture_color_highlight_frag.h shader_texture_color_highlight.frag
bin2c -o texture_color_highlight_vert.h shader_texture_color_highlight.vert
bin2c -o texture_alphamask_color_frag.h shader_texture_alphamask_color.frag
bin2c -o texture_alphamask_color_vert.h shader_texture_alphamask_color.vert
bin2c -o shader_render_depth_frag.h shader_render_depth.frag
bin2c -o shader_render_depth_vert.h shader_render_depth.vert
bin2c -o texture_lightmap_color_frag.h shader_texture_lightmap_color.frag
bin2c -o texture_lightmap_color_vert.h shader_texture_lightmap_color.vert
bin2c -o texture_blurmap_color_frag.h shader_texture_blurmap_color.frag
bin2c -o texture_blurmap_color_vert.h shader_texture_blurmap_color.vert
bin2c -o texture_blur_color_frag.h shader_texture_blur_color.frag
bin2c -o water_frag.h shader_water.frag
bin2c -o water_vert.h shader_water.vert
bin2c -o post_process_tonemapping.h shader_post_process_tonemapping.frag
bin2c -o post_process_bloom_filter_frag.h shader_post_process_bloom_filter.frag
bin2c -o post_process_empty_frag.h shader_post_process_empty.frag
bin2c -o post_process_empty_color_frag.h shader_post_process_empty_color.frag
bin2c -o post_process_vert.h shader_post_process.vert
bin2c -o post_process_color_vert.h shader_post_process_color.vert
bin2c -o post_process_blur_frag.h shader_post_process_blur.frag
bin2c -o post_process_vblur_vert.h shader_post_process_vblur.vert
bin2c -o post_process_hblur_vert.h shader_post_process_hblur.vert
bin2c -o post_process_bloom_add_filter_frag.h shader_post_process_bloom_add_filter.frag
bin2c -o post_process_bloom_depth_add_filter.h shader_post_process_bloom_depth_add_filter.frag
bin2c -o post_process_mix_frag.h shader_post_process_mix.frag
bin2c -o module_fog_vert.h module_fog.vert
